# Generated by Django 4.2.1 on 2023-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('DisplayName', models.CharField(max_length=200)),
                ('UserTag', models.CharField(max_length=200)),
                ('Awards', models.ManyToManyField(blank=True, to='match.award')),
            ],
        ),
    ]
