# Generated by Django 4.2.1 on 2023-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_surrender'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='AverageOppRank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='AverageRank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
