# Generated by Django 4.2.1 on 2023-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_averageopprank_match_averagerank'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='AverageOppRankSimple',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='AverageRankSimple',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
